### ISSUE TITLE
Is the time cut off?

### ISSUE THREAD

**Issue by robwilc** [nitr8/cet-dashboard#1]
On the Managed Operations overview page, is the Y axis label truncated?

![activemigrationstimespent](https://cloud.githubusercontent.com/assets/1247413/20670622/992ea218-b571-11e6-9b37-f36501f8699e.png)

**Comment by lukaszdrahal** [comment]
looks good now , I think I accidentally fixed this .when I rearranged legend size on other pages. (some piece of code is common here.)
check screenshot 

![image](https://cloud.githubusercontent.com/assets/23551626/21376437/46d5410e-c735-11e6-82bc-a3e6dec76d24.png)
