### ISSUE TITLE
TASK: Cases which have breached SLA on Mgmt Page

### ISSUE THREAD

**Issue by robwilc** [nitr8/cet-dashboard#10]
Currently it never shows any cases which have breached SLA. I suspect the query is wrong.

**Comment by lukaszdrahal** [comment]
right now we are using this query :

	SELECT swtickets.TicketID AS 'ID', swtickets.Ownerstaffname AS 'Owner', 
			from_unixtime(swtickets.dateline, '%Y %D %M %h:%i:%s') 
			As  
			'Opened', swtickets.Subject AS 'Case', swtickets.firstresponsetime AS 'frt', swtickets.priorityTitle as 'pr' , 
			swtickets.AverageResponseTime AS 'ar', swtickets.TotalReplies AS 'tr',  
			swtickets.TimeWorked AS 'tw', swtickets.ticketStatustitle AS 'Status', swuserorganizations.organizationname as 'on'
			FROM swtickets 
			left join swusers on swtickets.userid = swusers.userid 
			left join swuserorganizations on swusers.userorganizationid = swuserorganizations.userorganizationid 		
			WHERE swtickets.Departmenttitle ='CET' AND swtickets.isescalated = 1   AND swtickets.ticketStatustitle <> 'Closed' 
			AND swtickets.dateline > UNIX_TIMESTAMP(curdate()-INTERVAL 7 DAY)

**Comment by lukaszdrahal** [comment]
I think I should remove 
"AND swtickets.ticketStatustitle <> 'Closed'"

because when report is generated , ticket should be already closed
and also replace dateline range with 

AND swtickets.dateline > UNIX_TIMESTAMP(STR_TO_DATE('201650 Monday', '%X%V %W')) 
AND swtickets.dateline < UNIX_TIMESTAMP(STR_TO_DATE('201651 Monday', '%X%V %W')) ;

because we gathering stuff for every week ...

**Comment by lukaszdrahal** [comment]
right now we will use 

            	SELECT swtickets.TicketID AS 'ID', swtickets.Ownerstaffname AS 'Owner', 
			from_unixtime(swtickets.dateline, '%Y %D %M %h:%i:%s') 
			As  
			'Opened', swtickets.Subject AS 'Case', swtickets.firstresponsetime AS 'frt', swtickets.priorityTitle as 'pr' , 
			swtickets.AverageResponseTime AS 'ar', swtickets.TotalReplies AS 'tr',  
			swtickets.TimeWorked AS 'tw', swtickets.ticketStatustitle AS 'Status', swuserorganizations.organizationname as 'on'
			FROM swtickets 
			left join swusers on swtickets.userid = swusers.userid 
			left join swuserorganizations on swusers.userorganizationid = swuserorganizations.userorganizationid 		
			WHERE swtickets.Departmenttitle ='CET' AND swtickets.isescalated = 1  -- AND swtickets.ticketStatustitle <> 'Closed' 
			AND swtickets.dateline > UNIX_TIMESTAMP(STR_TO_DATE('201650 Monday', '%X%V %W')) 
			AND swtickets.dateline < UNIX_TIMESTAMP(STR_TO_DATE('201651 Monday', '%X%V %W')) ;



problem ist last escalated ticket is app from august 2014

**Comment by lukaszdrahal** [comment]
issue closed
