### ISSUE TITLE
Sort order of tickets

### ISSUE THREAD

**Issue by robwilc** [nitr8/cet-dashboard#12]
On the OPS-Overview page, change the sort order of the Daily Checks tickets to be alphabetical based on customer name.

**Comment by lukaszdrahal** [comment]
ordering changed : 

SELECT ticketid, subject, FROM_UNIXTIME(dateline) as created, timeworked ,FROM_UNIXTIME(lastactivity) as reply from  swtickets where ticketstatustitle = 'Daily Checks'  order by subject

**Comment by robwilc** [comment]
Like it
