### ISSUE TITLE
Sort order of drop down on graph

### ISSUE THREAD

**Issue by robwilc** [nitr8/cet-dashboard#13]
On the OPS Overview page, the graph at the lower right hand side allows you to select a customer from a list of customers.

Change the drop down list to order the customers alphabetically

**Comment by lukaszdrahal** [comment]
adjusted - now we will use

"SELECT ticketid,subject FROM ".KSQL_PRFX.".swtickets where ticketstatustitle = 'Daily Checks' order by subject

**Comment by robwilc** [comment]
Like it
