### ISSUE TITLE
Date controls in bad place

### ISSUE THREAD

**Issue by robwilc** [nitr8/cet-dashboard#14]
On the OPS Overview page, the date range controls are at the top of the page, but they refer to the chart at the bottom right of the page.

We should move them to the bottom right.. that way it will be clear to people that they need to click on APPLY.

Is there anyway to make it so that when you change the customer in the drop down list, it applies that change (rather than having to click on Apply) ?

**Comment by lukaszdrahal** [comment]
sure thing ...

**Comment by lukaszdrahal** [comment]
![image](https://cloud.githubusercontent.com/assets/23551626/21365512/e833c9f2-c6f5-11e6-835b-15b923c6bf29.png)

rearranged

**Comment by robwilc** [comment]
Like it.
