### ISSUE TITLE
Management Overview -> Urgent cases

### ISSUE THREAD

**Issue by robwilc** [nitr8/cet-dashboard#15]
Currently this gets the case list as tickets where 'flag' is set. These are escalated tickets in the new escalation process.

Should we:

a/ Change the query to get those, like now, and also tickets where the priority field is Urgent?

b/ Change the query to just get the ones where the priority field is urgent?

**Comment by lukaszdrahal** [comment]
right now we are using following query for sucking data : 

SELECT swtickets.TicketID AS 'ID', swtickets.Ownerstaffname AS 'Owner', 
from_unixtime(swtickets.dateline, '%Y %D %M %h:%i:%s') 
As  
'Opened', swtickets.Subject AS 'Case', swtickets.firstresponsetime AS 'frt', swtickets.priorityTitle as 'pr' , 
swtickets.AverageResponseTime AS 'ar', swtickets.TotalReplies AS 'tr',  
swtickets.TimeWorked AS 'tw', swtickets.ticketStatustitle AS 'Status', swuserorganizations.organizationname as 'on' 
FROM swtickets 
left join swusers on swtickets.userid = swusers.userid 
left join swuserorganizations on swusers.userorganizationid = swuserorganizations.userorganizationid 		
WHERE swtickets.Departmenttitle ='CET' AND swtickets.ticketStatustitle <> 'Closed' AND swtickets.priorityTitle = 'Urgent'

**Comment by lukaszdrahal** [comment]
after adjustment we will display all tickets - also these which are  closed already:


SELECT swtickets.TicketID AS 'ID', swtickets.Ownerstaffname AS 'Owner', 
from_unixtime(swtickets.dateline, '%Y %D %M %h:%i:%s') 
As  
'Opened', swtickets.Subject AS 'Case', swtickets.firstresponsetime AS 'frt', swtickets.priorityTitle as 'pr' , 
swtickets.AverageResponseTime AS 'ar', swtickets.TotalReplies AS 'tr',  
swtickets.TimeWorked AS 'tw', swtickets.ticketStatustitle AS 'Status', swuserorganizations.organizationname as 'on' 
FROM swtickets 
left join swusers on swtickets.userid = swusers.userid 
left join swuserorganizations on swusers.userorganizationid = swuserorganizations.userorganizationid 		
WHERE swtickets.Departmenttitle ='CET'  AND swtickets.priorityTitle = 'Urgent' 
AND swtickets.dateline > UNIX_TIMESTAMP(STR_TO_DATE('201610 Monday', '%X%V %W')) 
AND swtickets.dateline < UNIX_TIMESTAMP(STR_TO_DATE('201651 Monday', '%X%V %W')) ;

**Comment by robwilc** [comment]
Okay.
