### ISSUE TITLE
Managed Migration Customer Selection Page

### ISSUE THREAD

**Issue by robwilc** [nitr8/cet-dashboard#16]
For an individual logged in user, I want to be able to customize what is shown on the 'Ops' menu.

In other words, for FD people they won't need to see all the 'rubbish' relating to AS customers. Likewise each Ops person has specific customers that they are monitoring. They don't (usually) want to see other customers.

I suggest an ALPHABETICAL list based on the Ticket Type 'Daily Checks'. For each row we should indicate the ticket title (which is usually the customer), date ticket was created, date ticket was last updated (if possible) and the product. Those products that contain .Cloud should have a nicely coloured background.

Below the main list we should have 'closed' tickets shown (of type Daily Checks) so that we can pick recently closed Managed Operations.

On this screen we should be able to select (check boxes?) zero or more customers. 

These selected ones are different per logged in user. These selected ones will then be available on the drop down list of customers under Ops.

Also on this screen I want to be able to set the expected export / import GiB per day per row in the table.

**Comment by lukaszdrahal** [comment]
![image](https://cloud.githubusercontent.com/assets/23551626/21453883/1eca944e-c914-11e6-98e1-e247220243b3.png)
first draft ...
