### ISSUE TITLE
Managed Migration Customer Menu list

### ISSUE THREAD

**Issue by robwilc** [nitr8/cet-dashboard#17]
Following from:

Managed Migration Customer Selection Page

We need to show a menu drop down under 'Ops' which shows the customers that I have currently 'enabled' in my profile.

**Comment by lukaszdrahal** [comment]
something like this .. 

![image](https://cloud.githubusercontent.com/assets/23551626/21453866/02b536ce-c914-11e6-8afa-8d21840d0691.png)

**Comment by lukaszdrahal** [comment]
deployed .. now we got only some dummy data for endo
