### ISSUE TITLE
Improve individual charts

### ISSUE THREAD

**Issue by robwilc** [nitr8/cet-dashboard#2]
For example: 'Tickets by Product'...

The drops for the line graph at the bottom are hard to use.

![ticketsbyproduct](https://cloud.githubusercontent.com/assets/1247413/20670654/c1f1f6c8-b571-11e6-938c-bc6305e30312.png)

**Comment by lukaszdrahal** [comment]
why ?

**Comment by lukaszdrahal** [comment]
I am gonna close this :)
this really missing some useful description .. and on pc , like on PC , not mac it works perfect:-P

**Comment by robwilc** [comment]
Nice
