### ISSUE TITLE
Managed Migration - Overview Page

### ISSUE THREAD

**Issue by robwilc** [nitr8/cet-dashboard#26]
On the Managed Ops Overview page add a new table which shows:

- Ninja Name down the left

Then as columns
- Number of owned Managed Ops (Daily Checks) tickets which are open
- Total number of minutes logged this week on all Daily Checks tickets

**Comment by lukaszdrahal** [comment]
ok - this is good idea

**Comment by lukaszdrahal** [comment]
we will use this query for Total number of minutes logged this week on all Daily Checks tickets

SELECT swtickettimetracks.workerstaffname as dat ,sum(timespent) as ts FROM swtickettimetracks  left join swtickets on swtickettimetracks.ticketid = swtickets.ticketid 
where swtickettimetracks.dateline > UNIX_TIMESTAMP(adddate(curdate(), INTERVAL 1-DAYOFWEEK(curdate()) DAY))  group by workerstaffname

**Comment by lukaszdrahal** [comment]
![image](https://cloud.githubusercontent.com/assets/23551626/21370641/faa1d838-c70c-11e6-9126-9a98df55b513.png)

something like that ?

**Comment by lukaszdrahal** [comment]
that example was filled by dummy data ...

**Comment by robwilc** [comment]
The query you listed, doesn't have any filtering on TicketType = Daily Checks?
Can you check that please.

**Comment by lukaszdrahal** [comment]
Corrected : 

it's like this ... 
select '' as nr, ownerstaffname, count(ownerstaffname) as cnt, coalesce(a.ts,'0') as timespent from ".KSQL_TPRFX."tickets 
left join 
(SELECT swtickettimetracks.workerstaffname as workerstaffname ,sum(timespent) as ts FROM ".KSQL_TPRFX."tickettimetracks  
left join ".KSQL_TPRFX."tickets on ".KSQL_TPRFX."tickettimetracks.ticketid = ".KSQL_TPRFX."tickets.ticketid 
where ".KSQL_TPRFX."tickettimetracks.dateline > UNIX_TIMESTAMP(adddate(curdate(), INTERVAL 1-DAYOFWEEK(curdate()) DAY)) 
and ticketstatustitle='Daily Checks'  group by workerstaffname ) a 
on a.workerstaffname = ".KSQL_TPRFX."tickets.ownerstaffname 
where ticketstatustitle='Daily Checks' group by ownerstaffname

**Comment by lukaszdrahal** [comment]
so your daily check condition is on the bottom ...
