### ISSUE TITLE
Support Page

### ISSUE THREAD

**Issue by robwilc** [nitr8/cet-dashboard#28]
On the support page (at the bottom?) we should a list of expired KB's:

http://swish.ifu.local/ss/index.php?old=1

**Comment by lukaszdrahal** [comment]
because we have more space than on big screen, I added also two other columns which could be useful: 

![image](https://cloud.githubusercontent.com/assets/23551626/21368767/36250b4a-c704-11e6-9caa-0190b1dc0e6c.png)

**Comment by robwilc** [comment]
All good
