### ISSUE TITLE
Big Screen

### ISSUE THREAD

**Issue by robwilc** [nitr8/cet-dashboard#29]
We should add a list of expired KB's to the big screen page

http://swish.ifu.local/ss/index.php?old=1

**Comment by lukaszdrahal** [comment]
ok..

**Comment by lukaszdrahal** [comment]
I removed waynes weather - he will kick my ass, and replace it with top 5 expired KBs 

we need to adjust this because right now we got 436 kbs older than year ... 

![image](https://cloud.githubusercontent.com/assets/23551626/21367856/1b19c790-c700-11e6-8fd9-7a56b879947e.png)

**Comment by robwilc** [comment]
Confirmed ok
