### ISSUE TITLE
Man Ops -> Overview -> Daily time spent for.. graph

### ISSUE THREAD

**Issue by robwilc** [nitr8/cet-dashboard#32]
When I choose THIS MONTH.. the date pickers change to the right dates, but even when I click on APPLY, the chart still shows back to October last year.

**Comment by lukaszdrahal** [comment]
that's bad

**Comment by robwilc** [comment]
terrible.

**Comment by lukaszdrahal** [comment]
actually ... 

it's not wrong ... but position of this filter belongs to different "box"


![image](https://cloud.githubusercontent.com/assets/23551626/22140443/d17c3c76-deec-11e6-97c4-6b1f08e574c7.png)

I will move that ...

**Comment by lukaszdrahal** [comment]
done 
![image](https://cloud.githubusercontent.com/assets/23551626/22140630/d81a9d10-deed-11e6-8377-1ab839a023ca.png)
