### ISSUE TITLE
Closed Cases

### ISSUE THREAD

**Issue by robwilc** [nitr8/cet-dashboard#4]
I think we should update the columns as follows:

- Status = Not needed
It's closed cases so the status is closed on them all

- Opened (date / time)
The formating of this column is wrong. It should be: date. eg 21st November 2016

- Add Customer
The customer field should be visible, after the case title, before the 'first response'

**Comment by lukaszdrahal** [comment]
status removed, date time adjusted

**Comment by lukaszdrahal** [comment]
customer added
