### ISSUE TITLE
Charts at bottom of top 10 time takes is 'bad'

### ISSUE THREAD

**Issue by robwilc** [nitr8/cet-dashboard#7]
It has all customers in the drop down list - not just the ones that have Daily Check ticket (Ticket Type)....

It has them listed in some sort of strange random order -- not alphabetical

**Comment by nitr8** [comment]
this is now resolved it was an issue due to the fact that I had imported old data with no filitering, after you fixed the SQL query in #b8f4977e10c14e29301c0dc939c3d196c9e51b01

**Comment by robwilc** [comment]
Cool.
