### ISSUE TITLE
get CET dashboard to use bambooHR

### ISSUE THREAD

**Issue by nitr8** [nitr8/cet-dashboard#9]
Please see this:
https://www.bamboohr.com/api/documentation/time_off.php we need to use the API as an option in the settings and update cet/index and big_screen with it.

**Comment by lukaszdrahal** [comment]
done for big screen, done for support overview page. waynes pwd is not stored on GitHub :)

**Comment by lukaszdrahal** [comment]
![image](https://cloud.githubusercontent.com/assets/23551626/21977900/910867da-dbd8-11e6-9540-7021299c812e.png)
